### ISSUE TITLE
Add how to run other than workflow_run event

### ISSUE THREAD

**Issue by paper2** [paper2/github-actions-opentelemetry#106]
Github-actions-opentelemetry runs by only [workflow_run](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run) event.

If you want to run github-actions-opentelemetry with measured workflow, please reaction (👍 ) to this comment.

For example, github-actions-opentelemetry is not work well below.

```yaml
name: Example

on:
  workflow_dispatch:

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm build
      - uses: paper2/github-actions-opentelemetry@main
        ...
```
