### ISSUE TITLE
How Do I run this workflow for other branch

### ISSUE THREAD

**Issue by raghavgupta0** [paper2/github-actions-opentelemetry#107]
Hi Team,

I have created a separate Branch in my repo and tried to run below code, but it's not working
could you please help us here.

Also can we use tagging/labeling in "github-actions-opentelemetry" workflow

-----------------------------------------------------------
name: CI CD
on:
  workflow_dispatch:
  push:
    branches:
      - pipeline_test

jobs:
  build:
    runs-on: linux-x64-compute-small
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!!!!

------------------------------------------------------------------
name: Send Telemetry after Other Workflow

on:
  workflow_run:
    workflows: [CI CD]
    branches: [pipeline_test]
    # This action uses completed workflow for making traces and metrics.
    types:
      - completed

jobs:
  send-telemetry:
    name: Send CI Telemetry
    runs-on: linux-x64-compute-small
    steps:          
      - name: Run
        id: run
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: https://#####################
        with:
          # Required for collecting workflow data ##
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by paper2** [comment]
@raghavgupta0 
Thanks for opening this issue!!

This action can use workflow_run only.
https://github.com/paper2/github-actions-opentelemetry?tab=readme-ov-file#setup-instructions

**Comment by raghavgupta0** [comment]
Based in this https://github.com/paper2/github-actions-opentelemetry?tab=readme-ov-file#setup-instructions
I have tried below code but it's not working [working only for default branch (main/master)]

on:
workflow_run:
workflows: [CI CD]
branches: [pipeline_test]
# This action uses completed workflow for making traces and metrics.
types:
- completed

**Comment by paper2** [comment]
@raghavgupta0 
Hmm… I’m not sure what’s causing this issue. It looks like it should be working. The workflow_run event doesn’t trigger unless the workflow is merged into main, but you’ve already merged it, right…?

If you could create a repository that reproduces the issue, I could provide more detailed support.

**Comment by paper2** [comment]
@raghavgupta0 

Please write the YAML file in markdown format.

Example:

```yaml
name: CI Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
```
